CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       role VARCHAR(50) NOT NULL,
                       username VARCHAR(255) NOT NULL UNIQUE
);

-- changeSet id: 20250413-1
CREATE TABLE cards (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       card_number VARCHAR(255) NOT NULL UNIQUE,
                       user_id BIGINT NOT NULL,
                       expiry_date DATE NOT NULL,
                       status VARCHAR(50) NOT NULL,
                       balance DECIMAL(19,2) NOT NULL DEFAULT 0.00,
                       CONSTRAINT fk_cards_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- changeSet id: 20250413-2
CREATE TABLE limits (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        card_id BIGINT NOT NULL,
                        daily_limit DECIMAL(19,2) NOT NULL,
                        monthly_limit DECIMAL(19,2) NOT NULL,
                        CONSTRAINT fk_limits_card FOREIGN KEY (card_id) REFERENCES cards(id)
);

-- changeSet id: 20250413-3
CREATE TABLE transactions (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              amount DECIMAL(19,2) NOT NULL,
                              transaction_type VARCHAR(50) NOT NULL,
                              transaction_date TIMESTAMP NOT NULL,
                              source_card_id BIGINT NOT NULL,
                              target_card_id BIGINT,
                              CONSTRAINT fk_transactions_source_card FOREIGN KEY (source_card_id) REFERENCES cards(id),
                              CONSTRAINT fk_transactions_target_card FOREIGN KEY (target_card_id) REFERENCES cards(id)
);

-- changeSet id: 20250413-4
CREATE TABLE card_block_reasons (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    card_id BIGINT NOT NULL,
                                    reason VARCHAR(255),
                                    request_date TIMESTAMP,
                                    status VARCHAR(50)
);

ALTER TABLE card_block_reasons
    ADD CONSTRAINT fk_card_block_reasons_card
        FOREIGN KEY (card_id) REFERENCES cards(id);